apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: educates-lookup-service-installer.educates.dev
  namespace: educates-lookup-service-installer
spec:
  serviceAccountName: educates-lookup-service-installer
  syncPeriod: 87600h #! 10 years
  fetch:
  - imgpkgBundle:
      image: ghcr.io/educates/educates-lookup-service-installer:main
  template:
  - ytt:
      paths:
      - config
      valuesFrom:
      - secretRef:
          name: educates-lookup-service-values
  - kbld:
      paths:
      - .imgpkg/images.yml
      - '-'
  deploy:
  - kapp:
      rawOptions:
      - --app-changes-max-to-keep=5
