apiVersion: v1
kind: Secret
metadata:
  name: educates-lookup-service-values
  namespace: educates-lookup-service-installer
stringData:
  values.yml: |
    clusterIngress:
      domain: educates-local-dev.test
      tlsCertificateRef:
        namespace: educates
        name: educates-local-dev.test-tls
