#@ load("@ytt:data", "data")

#@ applicationNamespace = data.values.applicationNamespace.name

#@ ingressSecretName = data.values.clusterIngress.tlsCertificateRef.name
#@ ingressSecretNamespace = data.values.clusterIngress.tlsCertificateRef.namespace

#@ caCertificateSecretName = data.values.clusterIngress.caCertificateRef.name
#@ caCertificateSecretNamespace = data.values.clusterIngress.caCertificateRef.namespace

#@ if ingressSecretName:
#@ if ingressSecretNamespace != applicationNamespace:
---
apiVersion: secrets.educates.dev/v1beta1
kind: SecretCopier
metadata:
  name: educates-lookup-service-ingress-secret
spec:
  rules:
  - sourceSecret:
      name: #@ ingressSecretName
      namespace: #@ ingressSecretNamespace
    targetNamespaces:
      nameSelector:
        matchNames:
        - #@ applicationNamespace
#@ end
#@ end

#@ if caCertificateSecretName:
#@ if caCertificateSecretNamespace != applicationNamespace:
---
apiVersion: secrets.educates.dev/v1beta1
kind: SecretCopier
metadata:
  name: educates-lookup-service-ca-certificate-secret
spec:
  rules:
  - sourceSecret:
      name: #@ caCertificateSecretName
      namespace: #@ caCertificateSecretNamespace
    targetNamespaces:
      nameSelector:
        matchNames:
        - #@ applicationNamespace
#@ end
#@ end
